<table>
	<tr>
		<th>État</th>
		<th>Initiateur</th>
		<th>Titre</th>
	</tr>
	<?php
		while($row=$histo_dem){
			echo'<tr>
					<td>'.$row['dem_type'].'</td>
					<td>'.$row['pers_nom'].'</td>
					<td>'.$row['dem_titre'].'</td>
				</tr>'
	?>
</table>